Update MaterialDrawer to 6.0.9
It is the last version that uses AppCompat since we're not using AndroidX
and it fixes the issue below:

java.lang.IllegalArgumentException: Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed